### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Lymdun** [shipgirlproject/Haruna#10]
![](https://i.imgur.com/weTDUJD.png)

Hi~
Sadly, no more information than this, but when it happens, Haruna is not working anymore.

**Comment by Deivu** [comment]
This is the updated jar based from the latest commit. Please check and see if the issue still pops up in this commit.
https://amanogawa.moe/cdn/haruna-3.2.0-beta.jar

**Comment by Lymdun** [comment]
Seems fixed, thanks again!
