### ISSUE TITLE
Haruna sending spam like messages when user votes

### ISSUE THREAD

**Issue by itsmishra19** [shipgirlproject/Haruna#14]
I was restarting the Haruna and when it got ready it instantly received a vote and it sended the message 4 times instead of 1, and at normal times it's working fine

Images: https://cdn.discordapp.com/attachments/593768276732149780/860096288867614750/unknown.png

**Comment by Deivu** [comment]
If there is a stack trace, or debug logs on how this happens, please do include it so I can track it

**Comment by itsmishra19** [comment]
I think it was a issue on my side.
