### ISSUE TITLE
Gateway time-out causes crash

### ISSUE THREAD

**Issue by Lymdun** [shipgirlproject/Haruna#9]
![](https://i.imgur.com/x9Ts6bx.png)

Typo in the title: It doesn't crash, but Haruna isn't able anymore to receive POST requests when it happens.

**Comment by Deivu** [comment]
Thanks for reporting. I'll check around and see where this issue originates.

**Comment by Deivu** [comment]
Haruna is updated to 3.1.0 which I think fixes this issue. You can get the jar from the CI Server

**Comment by Lymdun** [comment]
Wow, you're really fast! Thanks, will test it as soon as possible

**Comment by Lymdun** [comment]
After two weeks, I can confirm that there was no crashes anymore, thanks!
